version: 1.0.{build}

branches:
  only:
  - master

configuration:
- Debug
- Release

platform: x86

before_build:
- cmd: >-
    cd vcproj
    cmake .. -G "Visual Studio 14 2015"

build:
  project: Intercept.sln
  parallel: true
  verbosity: minimal
