version: 1.0.{build}

branches:
  only:
  - master

configuration:
- Debug
- Release

platform: x86

build_script:
- cmd: >-
    cd vcproj

    cmake .. -G "Visual Studio 14 2015"

    msbuild Intercept.sln
